### ISSUE TITLE
Why not report on anonymous style objects created in render?

### ISSUE THREAD

**Issue by kevinSuttle** [cvazac/eslint-plugin-react-perf#10]
> The following patterns are not considered warnings:
```jsx
<div style={{display: 'none'}} />
```

This creates a new style object on every render. Better to initialize and reference, and because this is a static object, do so _outside_ of render. 

```jsx
const displayNone = {display: 'none'};

render() {
    return (<div style={displayNone} />)
}
```

See also: https://gist.github.com/ryanflorence/70f9ca97de0606212424694a3629428d#file-oh-no-jsx

**Comment by cvazac** [comment]
Thanks for the issue!

We are [purposefully excluding](https://github.com/cvazac/eslint-plugin-react-perf/blob/7919dfa291864206c7bc10e490c75c2bce4b164f/lib/utils/jsx-no-new-as-prop.js#L27) native HTML elements for the checks we run, but now I can't remember why. :( 

Seems to me that it would still cause React to reconcile the differences, which we could certainly avoid here. I will do  some experimentation and probably remove all of the `isNativeElement` checks. 

You have any recollection of this @vbud?

**Comment by vbud** [comment]
Did we add it for something like:

```
<Component headerControl={<div>hello</div>}/>
```

**Comment by cvazac** [comment]
Using [this](https://github.com/cvazac/test-ref-pattern) I can see that there is a performance hit for even native HTML components, although less pronounced that others. I will remove the `isNativeElement()` checks ASAP.

**Comment by kevinSuttle** [comment]
Sorry, trying to follow the events here. Is the original request part of this?

**Comment by kevinSuttle** [comment]
Awesome, thank you!

**Comment by cvazac** [comment]
This should be  covered by "jsx-no-jsx-as-prop", FYI.

> Did we add it for something like:
> 
> ```
> <Component headerControl={<div>hello</div>}/>
> ```
