### ISSUE TITLE
Exceptions option to jsx-no-new-object-as-prop and jsx-no-new-array-as-prop

### ISSUE THREAD

**Issue by emattias** [cvazac/eslint-plugin-react-perf#19]
Emotion adds the possibility to pass a [css prop](https://emotion.sh/docs/css-prop#object-styles) to all components that takes an object (of styling). It gets hoisted away with their [babel plugin](https://emotion.sh/docs/@emotion/babel-preset-css-prop).

It would be nice to not have to globally disable the `jsx-no-new-object-as-prop` and `jsx-no-new-array-as-prop` (css prop can take an array also for style composition) rules or add a disable comment everywhere I add css 😅.

I am thinking something like this:

```js
rules: {
  'jsx-no-new-object-as-prop': [
    'error', 
    { 
      exceptProps: ['css'], 
    }
  ],
}
```
or
```js
rules: {
  'jsx-no-new-object-as-prop': ['error', 'css'],
}
```
or
```js
rules: {
  'jsx-no-new-object-as-prop': ['error', ['css']],
}
```

**Comment by cvazac** [comment]
If the `css` attribute is only ever present on "native" (lower-case first character) elements for Emotion, we _could_ assume the developer knows what she is doing and always ignore it in that case. 

Otherwise, I'll look for existing patterns of eslint plugins receiving config.

**Comment by jmancherje** [comment]
Just checking in on the status here. Is there any way to add specific exceptions in the config? Our app uses an internal UI library that we pass style objects to and I'd like to add that as an exception, there's too many occurrences to add an eslint-disable line

**Comment by cvazac** [comment]
I think specifying an exclude list as @emattias suggested is the best way to go here - that would work for you @jmancherje?

**Comment by cvazac** [comment]
@jmancherje correct - I need to add this.

**Comment by cvazac** [comment]
fixed with the `nativeAllowList` configuration as of v3.3.0
