### ISSUE TITLE
Question about the react-perf/jsx-no-new-object-as-prop rule

### ISSUE THREAD

**Issue by medialwerk** [cvazac/eslint-plugin-react-perf#20]
Hi guys,

thanks for this great plugin! :-). I recently updated the library to version 3.1.0 and first of all, I was pleased with the new rules. But then I had an issue while refactoring the code:

I easily can refactor the "new objects" which are not related to the props:

```js
render() {
   const style = {color: red};
    return (<div style={style} />)
}
```

No Problem. But I can't remove the "new objects" if they're related to the props because it has to be a new object in this case :

 ```js
render() {
   const style = {left: this.props.left};
    return (<div style={style} />)
}
```

In our application, we have to calculate many inline styles (which can not be replaced by pure CSS). I don't want to disable the rule (by comment) above all style attributes, neither I want to disable the rule completely because it makes total sense in our project.
Is there a solution to this?

thank you very much

**Comment by cvazac** [comment]
Thanks for the issue! 

[I've tested this](https://github.com/cvazac/eslint-plugin-react-perf/issues/10#issuecomment-453563603) and the performance degradation of passing an object as props to native elements like `<div>` is very minimal. I have a view with 10,000 `<div>`s and I'm passing a style object with 13 keys, and I'm only seeing a ~7% performance degradation between `componentWillUpdate()` and `componentDidUpdate().

That said, I think the right thing would be to make reporting against native elements an option. 

We could split each rules in two:
jsx-no-new-object-as-prop
jsx-no-new-object-as-prop-native
jsx-no-new-array-as-prop
jsx-no-new-array-as-prop-native
etc.

**Comment by medialwerk** [comment]
Thank you for the performance test, very interesting. But within our code-base, the only issue where we can't satisfy the actual linting rules is the `style` attribute (on native elements of course). So it would be cool to only disable it for that attribute.

**Comment by cvazac** [comment]
But, I don't think that `style` is a special case in React. 

```
  render() {
    const style = {};
    Object.defineProperty(style, "background", {
      get: () => {
        console.info("trapped");
        return "green";
      },
      enumerable: true
    });
    return <div style={style} />
  }
```

Using that snippet, you can see that the reconciler has to manually compare each (only `background` in this case) property. 

If `style` was assigned to the instance instead, that reconciliation doesn't take place. 

I know the comparisons are super fast, but it is extra work that React has to do. Which was the motivation behind this plugin to begin with. 

If you had these on:
jsx-no-new-object-as-prop
jsx-no-new-array-as-prop
jsx-no-new-function-as-prop

And these off:
jsx-no-new-object-as-prop-native
jsx-no-new-array-as-prop-native
jsx-no-new-function-as-prop-native

Would that work for you? 🤞

**Comment by cvazac** [comment]
fixed with the `nativeAllowList` configuration as of v3.3.0
