### ISSUE TITLE
Rule request: no-function-array-object-as-default-prop-destructuring

### ISSUE THREAD

**Issue by JustFly1984** [cvazac/eslint-plugin-react-perf#21]
There is an issue with refactoring from defaultProps to default values on prop destructuring

https://github.com/reactjs/rfcs/pull/107#issuecomment-499676229

Since Dan Abramov's tweet https://twitter.com/dan_abramov, it should be common refactoring issue.

**Comment by FredyC** [comment]
https://twitter.com/dan_abramov/status/1133878326358171650

_(you found that tweet initially, no credit for me here)_

**Comment by cvazac** [comment]
Thanks very much for the suggestion. I beefed up the scope check, no need for a new rule. Shipped in eslint-plugin-react-perf@3.2.0.

https://twitter.com/vazac/status/1137187888385396736
