### ISSUE TITLE
Add support for eslint@^6

### ISSUE THREAD

**Issue by JustFly1984** [cvazac/eslint-plugin-react-perf#27]
I see errors in terminal console on yarn install:

<img width="458" alt="Screenshot 2019-08-08 19 59 24" src="https://user-images.githubusercontent.com/2255993/62722428-0c024400-ba17-11e9-8074-a872b0b4aba2.png">

**Comment by cvazac** [comment]
Fixed in eslint-plugin-react-perf@3.2.1 thanks to @znewton :)
