### ISSUE TITLE
nativeAllowList use case

### ISSUE THREAD

**Issue by jdanil** [cvazac/eslint-plugin-react-perf#41]
Hey there. I was just checking out the changes in 3.3.0.
I'm wondering what the motivation is for the nativeAllowList.
Are there no performance costs of passing objects/arrays to native attributes, or is there another reason one might want to allow them?

**Comment by cvazac** [comment]
The performance cost for native (lowercase first letter) elements [exists but is minimal](https://github.com/cvazac/eslint-plugin-react-perf/issues/20#issuecomment-495059089). React still has to [reconcile all attributes](https://github.com/cvazac/eslint-plugin-react-perf/issues/20#issuecomment-520676439) on native elements. 

Adding the `nativeAllowList` configuration option is just intended to give users of the plugin the flexibility to not care about native elements. I will still be linting against native elements in my projects. :)

**Comment by jdanil** [comment]
Ahh great. Thanks for the clarification. I missed those threads.
