### ISSUE TITLE
Support for Eslint 4

### ISSUE THREAD

**Issue by medialwerk** [cvazac/eslint-plugin-react-perf#5]
Hello,
the plugin currently not supports the newest version of Eslint. Are you able to fix this?

`npm ERR! peer dep missing: eslint@^2.0.0 || ^3.0.0, required by eslint-plugin-react-perf@2.0.5`

Thanks!

**Comment by cvazac** [comment]
thanks for reporting!

version 2.0.6 should work for you, please let me know.

**Comment by medialwerk** [comment]
It seems that everything is fine except the npm error :-)

**Comment by cvazac** [comment]
Sorry for not being clearer, try installing eslint-plugin-react-perf @ 2.0.6, which has this change:
https://github.com/cvazac/eslint-plugin-react-perf/commit/bff36b22aff9640740c3c6b3234e86e830b7cc47

I'm thinking you won't get any npm error.

**Comment by medialwerk** [comment]
Thanks, that was really fast! :-)
