### ISSUE TITLE
Update peerDependencies to include `|| ^5.0.0` for eslint

### ISSUE THREAD

**Issue by chrisdhaan** [cvazac/eslint-plugin-react-perf#9]
`eslint` recently released version `5.0.0`. Would it be possible to add that version as a usable peerDependency in `package.json`?

**Comment by cvazac** [comment]
Sounds like we should definitely update that. 

Can you show me what you are seeing, please? I have eslint@5.0.0 installed locally and I am not seeing any warnings on install.

**Comment by chrisdhaan** [comment]
@cvazac I've included an image with the wanting I'm seeing

<img width="771" alt="eslint-plugin-react-perf-warning" src="https://user-images.githubusercontent.com/5225621/43166531-a269981e-8f4b-11e8-8883-7d10c94b6639.png">

**Comment by cvazac** [comment]
Thanks for the info! 2.0.9 has the fix.
